# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3ZgFnpojWD0Q53SIr67IlxH9M_gndMj

# **1. Instalación de recursos**
"""

!pip install streamlit -q
!pip install joblib -q

"""# **2. Lectura pkl e importación de clases**"""

import joblib
import os
from transformadores import LimpiezaInicial, ImputacionNulos, AgrupacionCCS

ruta = "modelo_final_pipeline.pkl"

if os.path.exists(ruta):
    artefacto = joblib.load(ruta)
    print("Artefacto cargado correctamente")
    print(f"  Versión   : {artefacto['version']}")
    print(f"  Clases    : {artefacto['clases']}")
    print(f"  Variables : {artefacto['variables_modelo']}")
    print(f"\nOpciones por variable:")
    for col, opts in artefacto['opciones'].items():
        print(f"  {col}: {len(opts)} categorías → {opts[:3]}...")
else:
    print("modelo_final_pipeline.pkl no encontrado")

"""#. **3. Prueba de predicción (sin interfaz)**"""

import pandas as pd

pipeline = artefacto["pipeline"]
opciones = artefacto["opciones"]

# Caso de prueba usando opciones reales del artefacto
paciente_prueba = pd.DataFrame([{
    "Age Group":                    opciones["Age Group"][-1],
    "Type of Admission":            "Emergency",
    "APR DRG Code":                 opciones["APR DRG Code"][0],
    "APR MDC Code":                 opciones["APR MDC Code"][0],
    "APR Severity of Illness Code": "3",
    "APR Risk of Mortality":        "Major",
    "Payment Typology 1":           "Medicare",
    "CCS_DX_Grupo":                 "Circulatorio",
    "CCS_PR_Grupo":                 "Cardiovascular"
}])

for col in paciente_prueba.columns:
    paciente_prueba[col] = paciente_prueba[col].astype("category")

try:
    prediccion = pipeline.predict(paciente_prueba)[0]
    print(f"Predicción: {prediccion}")
    if prediccion == "Corta":
        print("→ Estadía estimada: 1 a 3 días")
    elif prediccion == "Media":
        print("→ Estadía estimada: 4 a 7 días")
    else:
        print("→ Estadía estimada: 8 días o más")
except Exception as e:
    print(f"Error: {e}")

"""# **4. STreamlit**"""

app_codigo = '''import streamlit as st
import joblib
import pandas as pd
import os

st.set_page_config(
    page_title="Predictor de Estadía Hospitalaria",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\');
html, body, [class*="css"] { font-family: \'Inter\', sans-serif; background-color: #E6F0FA; }
[data-testid="stSidebar"] { background-color: #0D1B2A !important; }
[data-testid="stSidebar"] * { color: #FFFFFF !important; }
[data-testid="stSidebar"] small { color: #A7F3D0 !important; }
.card-header { font-size: 12px; font-weight: 600; color: #334155; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 14px; border-bottom: 2px solid #E6F0FA; padding-bottom: 8px; }
.result-corta { background: linear-gradient(135deg, #A7F3D0 0%, #E6F0FA 100%); border-left: 6px solid #0EA5A4; border-radius: 14px; padding: 28px; }
.result-media { background: linear-gradient(135deg, #FEF9C3 0%, #E6F0FA 100%); border-left: 6px solid #F59E0B; border-radius: 14px; padding: 28px; }
.result-larga { background: linear-gradient(135deg, #FEE2E2 0%, #E6F0FA 100%); border-left: 6px solid #EF4444; border-radius: 14px; padding: 28px; }
.result-title { font-size: 26px; font-weight: 700; color: #0D1B2A; margin-bottom: 4px; }
.result-subtitle { font-size: 14px; color: #334155; margin-bottom: 12px; }
.disclaimer { background: #F1F5F9; border-left: 4px solid #1E3A8A; border-radius: 8px; padding: 14px 18px; font-size: 12px; color: #334155; margin-top: 20px; line-height: 1.7; }
.ref-card { border-radius: 10px; padding: 12px 16px; margin-bottom: 8px; font-size: 13px; line-height: 1.5; }
.ref-corta { background: #A7F3D0; border-left: 4px solid #0EA5A4; }
.ref-media { background: #FEF9C3; border-left: 4px solid #F59E0B; }
.ref-larga { background: #FEE2E2; border-left: 4px solid #EF4444; }
.stButton > button { background-color: #1E3A8A !important; color: white !important; border-radius: 10px !important; padding: 12px 32px !important; font-size: 15px !important; font-weight: 600 !important; border: none !important; width: 100%; }
h1 { color: #0D1B2A !important; font-weight: 700 !important; font-size: 28px !important; }
h2 { color: #1E3A8A !important; font-weight: 600 !important; font-size: 20px !important; }
</style>
""", unsafe_allow_html=True)

# ── Carga del modelo ──────────────────────────────────────────
@st.cache_resource
def cargar_modelo():
    from transformadores import LimpiezaInicial, ImputacionNulos, AgrupacionCCS
    return joblib.load("modelo_final_pipeline.pkl")

try:
    artefacto = cargar_modelo()
    pipeline  = artefacto["pipeline"]
    opciones  = artefacto["opciones"]
    modelo_ok = True
except Exception as e:
    modelo_ok = False
    st.error(f"Error al cargar el modelo: {e}")

# ── Sidebar ───────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style="padding:8px 0 16px 0;">
        <span style="font-size:18px;font-weight:700;">Sistema de Apoyo Clínico</span><br>
        <span style="font-size:13px;color:#A7F3D0;">Predicción de Estadía Hospitalaria</span>
    </div>
    """, unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("""
    <div style="font-size:13px;line-height:1.8;">
        <b>Instrucciones</b><br>
        1. Complete todos los campos<br>
        2. Presione <b>Predecir</b><br>
        3. Revise el resultado y el aviso legal
    </div>
    """, unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("<div style=\'font-size:13px;\'><b>Referencia de categorías</b></div>",
                unsafe_allow_html=True)
    st.markdown("""
    <div class="ref-card ref-corta">
        <b>Estadía Corta</b> — 1 a 3 días<br>
        <small>Procedimientos rutinarios o condiciones manejables</small>
    </div>
    <div class="ref-card ref-media">
        <b>Estadía Media</b> — 4 a 7 días<br>
        <small>Tratamientos moderados con seguimiento activo</small>
    </div>
    <div class="ref-card ref-larga">
        <b>Estadía Larga</b> — 8 días o más<br>
        <small>Casos complejos o con riesgo de complicaciones</small>
    </div>
    """, unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("<small style=\'color:#A7F3D0;\'>v1.0.0 · SVM · SPARCS NY 2015</small>",
                unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────
st.markdown("""
<h1>Predictor de Duración de Estadía Hospitalaria</h1>
<p style="color:#334155;font-size:14px;margin-top:4px;">
    Herramienta de apoyo a la planificación de recursos hospitalarios.
    Complete los datos clínicos del paciente para obtener una estimación de la duración de la estadía.
</p>
""", unsafe_allow_html=True)
st.markdown("---")

# ── Formulario ────────────────────────────────────────────────
st.markdown("<h2>Datos del Paciente</h2>", unsafe_allow_html=True)

with st.form("formulario"):
    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("<div class=\'card-header\'>Información General</div>",
                    unsafe_allow_html=True)
        age_group     = st.selectbox("Grupo de edad",
                            opciones["Age Group"])
        tipo_admision = st.selectbox("Tipo de admisión",
                            opciones["Type of Admission"])
        pago          = st.selectbox("Tipo de pago principal",
                            opciones["Payment Typology 1"])

    with col2:
        st.markdown("<div class=\'card-header\'>Clasificación Clínica</div>",
                    unsafe_allow_html=True)
        sev_raw  = st.selectbox("Severidad de la enfermedad (APR SOI)",
                        opciones["APR Severity of Illness Code"])
        mor_raw  = st.selectbox("Riesgo de mortalidad (APR ROM)",
                        opciones["APR Risk of Mortality"])
        apr_mdc  = st.selectbox("Categoría diagnóstica mayor (APR MDC)",
                        opciones["APR MDC Code"])
        apr_drg  = st.selectbox("Grupo diagnóstico APR-DRG",
                        opciones["APR DRG Code"])

    with col3:
        st.markdown("<div class=\'card-header\'>Diagnóstico y Procedimiento</div>",
                    unsafe_allow_html=True)
        dx_grupo = st.selectbox("Grupo diagnóstico CCS",
                        opciones["CCS_DX_Grupo"])
        pr_grupo = st.selectbox("Grupo procedimiento CCS",
                        opciones["CCS_PR_Grupo"])

    submitted = st.form_submit_button("Predecir Duración de Estadía")

# ── Resultado ─────────────────────────────────────────────────
if submitted and modelo_ok:
    input_data = pd.DataFrame([{
        "Age Group":                    age_group,
        "Type of Admission":            tipo_admision,
        "APR DRG Code":                 apr_drg,
        "APR MDC Code":                 apr_mdc,
        "APR Severity of Illness Code": sev_raw,
        "APR Risk of Mortality":        mor_raw,
        "Payment Typology 1":           pago,
        "CCS_DX_Grupo":                 dx_grupo,
        "CCS_PR_Grupo":                 pr_grupo
    }])

    for col in input_data.columns:
        input_data[col] = input_data[col].astype("category")

    try:
        prediccion = pipeline.predict(input_data)[0]

        st.markdown("---")
        st.markdown("<h2>Resultado de la Predicción</h2>", unsafe_allow_html=True)
        col_res, col_info = st.columns([1, 1])

        with col_res:
            if prediccion == "Corta":
                st.markdown("""
                <div class="result-corta">
                    <div class="result-title">Estadía Corta</div>
                    <div class="result-subtitle">Estimación: <b>1 a 3 días</b></div>
                    <p style="font-size:14px;color:#334155;">
                        El modelo estima una hospitalización de corta duración, asociada
                        a procedimientos rutinarios o condiciones clínicamente manejables.
                    </p>
                </div>""", unsafe_allow_html=True)
            elif prediccion == "Media":
                st.markdown("""
                <div class="result-media">
                    <div class="result-title">Estadía Media</div>
                    <div class="result-subtitle">Estimación: <b>4 a 7 días</b></div>
                    <p style="font-size:14px;color:#334155;">
                        El modelo estima una hospitalización de duración moderada, con
                        tratamientos que requieren seguimiento clínico activo.
                    </p>
                </div>""", unsafe_allow_html=True)
            else:
                st.markdown("""
                <div class="result-larga">
                    <div class="result-title">Estadía Larga</div>
                    <div class="result-subtitle">Estimación: <b>8 días o más</b></div>
                    <p style="font-size:14px;color:#334155;">
                        El modelo estima una hospitalización prolongada, asociada a casos
                        de alta complejidad clínica o riesgo de complicaciones.
                    </p>
                </div>""", unsafe_allow_html=True)

        with col_info:
            st.markdown("<h3 style=\'font-size:15px;color:#334155;\'>Resumen de entrada</h3>",
                        unsafe_allow_html=True)
            st.dataframe(pd.DataFrame({
                "Variable": ["Edad","Admisión","Severidad","Mortalidad",
                             "Diagnóstico CCS","Procedimiento CCS",
                             "APR MDC","APR DRG","Pago"],
                "Valor":    [age_group, tipo_admision, sev_raw, mor_raw,
                             dx_grupo, pr_grupo, apr_mdc, apr_drg, pago]
            }), hide_index=True, use_container_width=True)

        st.markdown("""
        <div class="disclaimer">
            <b>Aviso importante sobre el uso de esta herramienta</b><br><br>
            Este sistema utiliza un modelo de clasificación supervisada (Support Vector Machine)
            entrenado con datos históricos del sistema SPARCS del Estado de Nueva York (2015),
            con un <b>F1-macro de 0.59</b> sobre datos de prueba independientes.<br><br>
            El <b>F1-macro</b> mide el balance entre precisión y recall promediado entre las
            tres categorías de estadía (Corta, Media, Larga), otorgando igual peso a cada clase.
            Un valor de 0.59 indica capacidad de clasificación moderada — el modelo clasifica
            correctamente aproximadamente 6 de cada 10 casos por categoría.<br><br>
            <b>Esta predicción es únicamente una herramienta de apoyo a la planificación
            administrativa y NO reemplaza el criterio clínico del personal médico.</b>
            Las decisiones sobre hospitalización, tratamiento y alta deben tomarse exclusivamente
            por profesionales de la salud habilitados, considerando la condición individual
            del paciente. Los desarrolladores y la institución no asumen responsabilidad
            por decisiones clínicas basadas en el resultado de este sistema.
        </div>
        """, unsafe_allow_html=True)

    except Exception as e:
        st.error(f"Error en la predicción: {e}")
'''

with open("app.py", "w") as f:
    f.write(app_codigo)

#requiements.txt
reqs = """streamlit
joblib
pandas
numpy
scikit-learn
imbalanced-learn
"""

with open("requirements.txt", "w") as f:
    f.write(reqs)
print(reqs)